/********************************************************************************
** Form generated from reading UI file 'MainWindow.ui'
**
** Created by: Qt User Interface Compiler version 5.13.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGridLayout>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHBoxLayout>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QSplitter>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QToolBox>
#include <QtWidgets/QToolButton>
#include <QtWidgets/QTreeView>
#include <QtWidgets/QVBoxLayout>
#include <QtWidgets/QWidget>
#include "QVTKOpenGLWidget.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindowClass
{
public:
    QAction *actionExit;
    QAction *actionOpen_DicomDir_File;
    QAction *actionUpdate_scene;
    QAction *actionUpdate_window_level_settings;
    QAction *actionAxial_move;
    QAction *actionSave_to_Dicom;
    QAction *actionOpen_Dicom_Folder_and_predicted_channel_file;
    QAction *actionSave_to_Stl;
    QAction *actionApply_Hounsfield_filter;
    QAction *actionMove_to_slice;
    QAction *actionUpdate_axial_normale;
    QAction *actionUse_voi;
    QAction *actionSave_axial_slice_to_Png;
    QAction *actionSaveSaggitalToPng;
    QAction *actionSaveCoronalToPng;
    QAction *actionSaveAxialToPng;
    QAction *actionUpdate_volume_property_settings;
    QAction *actionVOI_actor;
    QAction *actionAxial_slice_actor;
    QAction *actionSagittal_slice_actor;
    QAction *actionCoronal_slice_actor;
    QAction *action3D_actor;
    QWidget *centralWidget;
    QVBoxLayout *verticalLayout_2;
    QSplitter *splitter;
    QWidget *horizontalLayoutWidget;
    QHBoxLayout *horizontalLayout;
    QToolBox *toolBox;
    QWidget *page;
    QVBoxLayout *verticalLayout;
    QTreeView *dicomDirView;
    QWidget *page_2;
    QVBoxLayout *verticalLayout_3;
    QVBoxLayout *parWindowLevelToobar;
    QTableWidget *tableWindowLevelPreset;
    QGroupBox *groupBox_4;
    QHBoxLayout *horizontalLayout_2;
    QLabel *label_61;
    QLineEdit *curWindow;
    QLabel *label_62;
    QLineEdit *curLevel;
    QWidget *page_3;
    QVBoxLayout *verticalLayout_5;
    QVBoxLayout *parVolumePropertyToolbar;
    QTableWidget *tableVolumePropertyPreset;
    QWidget *page_4;
    QCheckBox *fResliceMode;
    QGroupBox *groupBox;
    QLabel *label;
    QLineEdit *saggital_Origin_X;
    QLineEdit *saggital_Origin_Y;
    QLabel *label_2;
    QLineEdit *saggital_Origin_Z;
    QLabel *label_3;
    QLineEdit *saggital_UL_X;
    QLineEdit *saggital_UL_Y;
    QLabel *label_4;
    QLabel *label_5;
    QLineEdit *saggital_UL_Z;
    QLabel *label_6;
    QLineEdit *saggital_LR_Z;
    QLabel *label_7;
    QLineEdit *saggital_LR_Y;
    QLineEdit *saggital_LR_X;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLineEdit *saggital_N_X;
    QLineEdit *saggital_N_Y;
    QLabel *label_14;
    QLabel *label_15;
    QLineEdit *saggital_N_Z;
    QLabel *label_16;
    QLabel *label_17;
    QLineEdit *saggital_C_X;
    QLabel *label_18;
    QLineEdit *saggital_C_Y;
    QLabel *label_19;
    QLabel *label_20;
    QLineEdit *saggital_C_Z;
    QGroupBox *groupBox_2;
    QLabel *label_21;
    QLineEdit *coronal_Origin_X;
    QLineEdit *coronal_Origin_Y;
    QLabel *label_22;
    QLineEdit *coronal_Origin_Z;
    QLabel *label_23;
    QLineEdit *coronal_UL_X;
    QLineEdit *coronal_UL_Y;
    QLabel *label_24;
    QLabel *label_25;
    QLineEdit *coronal_UL_Z;
    QLabel *label_26;
    QLineEdit *coronal_LR_Z;
    QLabel *label_27;
    QLineEdit *coronal_LR_Y;
    QLineEdit *coronal_LR_X;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLineEdit *coronal_N_X;
    QLineEdit *coronal_N_Y;
    QLabel *label_34;
    QLabel *label_35;
    QLineEdit *coronal_N_Z;
    QLabel *label_36;
    QLabel *label_37;
    QLineEdit *coronal_C_X;
    QLabel *label_38;
    QLineEdit *coronal_C_Y;
    QLabel *label_39;
    QLabel *label_40;
    QLineEdit *coronal_C_Z;
    QGroupBox *groupBox_3;
    QLabel *label_41;
    QLineEdit *axial_Origin_X;
    QLineEdit *axial_Origin_Y;
    QLabel *label_42;
    QLineEdit *axial_Origin_Z;
    QLabel *label_43;
    QLineEdit *axial_UL_X;
    QLineEdit *axial_UL_Y;
    QLabel *label_44;
    QLabel *label_45;
    QLineEdit *axial_UL_Z;
    QLabel *label_46;
    QLineEdit *axial_LR_Z;
    QLabel *label_47;
    QLineEdit *axial_LR_Y;
    QLineEdit *axial_LR_X;
    QLabel *label_48;
    QLabel *label_49;
    QLabel *label_50;
    QLabel *label_51;
    QLabel *label_52;
    QLabel *label_53;
    QLineEdit *axial_N_X;
    QLineEdit *axial_N_Y;
    QLabel *label_54;
    QLabel *label_55;
    QLineEdit *axial_N_Z;
    QLabel *label_56;
    QLabel *label_57;
    QLineEdit *axial_C_X;
    QLabel *label_58;
    QLineEdit *axial_C_Y;
    QLabel *label_59;
    QLabel *label_60;
    QLineEdit *axial_C_Z;
    QLabel *label_63;
    QLineEdit *slicePos;
    QLabel *label_64;
    QLineEdit *sliceIndex;
    QLabel *label_67;
    QLineEdit *yDegree;
    QToolButton *planeSavePngChoice;
    QWidget *page_5;
    QVBoxLayout *verticalLayout_4;
    QVBoxLayout *parHounsfieldFilterToolbar;
    QGroupBox *groupBox_5;
    QLabel *label_66;
    QLabel *label_65;
    QDoubleSpinBox *minHounsfieldFilter;
    QDoubleSpinBox *maxHounsfieldFilter;
    QWidget *horizontalLayoutWidget_2;
    QHBoxLayout *horizontalLayout_3;
    QTabWidget *tabWidget;
    QWidget *tab;
    QHBoxLayout *horizontalLayout_4;
    QGridLayout *gridLayout;
    QVTKOpenGLWidget *view1;
    QVTKOpenGLWidget *view3;
    QVTKOpenGLWidget *view4;
    QVTKOpenGLWidget *view2;
    QWidget *tab_2;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuView;
    QMenu *menu3D_Actor_View;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindowClass)
    {
        if (MainWindowClass->objectName().isEmpty())
            MainWindowClass->setObjectName(QString::fromUtf8("MainWindowClass"));
        MainWindowClass->resize(557, 596);
        actionExit = new QAction(MainWindowClass);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/MainWindow/Exit.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionExit->setIcon(icon);
        actionOpen_DicomDir_File = new QAction(MainWindowClass);
        actionOpen_DicomDir_File->setObjectName(QString::fromUtf8("actionOpen_DicomDir_File"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/MainWindow/Folder.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionOpen_DicomDir_File->setIcon(icon1);
        actionUpdate_scene = new QAction(MainWindowClass);
        actionUpdate_scene->setObjectName(QString::fromUtf8("actionUpdate_scene"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/MainWindow/Modify.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionUpdate_scene->setIcon(icon2);
        actionUpdate_window_level_settings = new QAction(MainWindowClass);
        actionUpdate_window_level_settings->setObjectName(QString::fromUtf8("actionUpdate_window_level_settings"));
        actionUpdate_window_level_settings->setCheckable(true);
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/MainWindow/Update.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionUpdate_window_level_settings->setIcon(icon3);
        actionAxial_move = new QAction(MainWindowClass);
        actionAxial_move->setObjectName(QString::fromUtf8("actionAxial_move"));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/MainWindow/Go.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionAxial_move->setIcon(icon4);
        actionSave_to_Dicom = new QAction(MainWindowClass);
        actionSave_to_Dicom->setObjectName(QString::fromUtf8("actionSave_to_Dicom"));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/MainWindow/Save.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSave_to_Dicom->setIcon(icon5);
        actionOpen_Dicom_Folder_and_predicted_channel_file = new QAction(MainWindowClass);
        actionOpen_Dicom_Folder_and_predicted_channel_file->setObjectName(QString::fromUtf8("actionOpen_Dicom_Folder_and_predicted_channel_file"));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/MainWindow/iconfinder_52_62709.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionOpen_Dicom_Folder_and_predicted_channel_file->setIcon(icon6);
        actionSave_to_Stl = new QAction(MainWindowClass);
        actionSave_to_Stl->setObjectName(QString::fromUtf8("actionSave_to_Stl"));
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/MainWindow/Floppy-icon.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSave_to_Stl->setIcon(icon7);
        actionApply_Hounsfield_filter = new QAction(MainWindowClass);
        actionApply_Hounsfield_filter->setObjectName(QString::fromUtf8("actionApply_Hounsfield_filter"));
        actionApply_Hounsfield_filter->setCheckable(true);
        actionApply_Hounsfield_filter->setIcon(icon3);
        actionMove_to_slice = new QAction(MainWindowClass);
        actionMove_to_slice->setObjectName(QString::fromUtf8("actionMove_to_slice"));
        QIcon icon8;
        icon8.addFile(QString::fromUtf8(":/MainWindow/Forward.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionMove_to_slice->setIcon(icon8);
        actionUpdate_axial_normale = new QAction(MainWindowClass);
        actionUpdate_axial_normale->setObjectName(QString::fromUtf8("actionUpdate_axial_normale"));
        QIcon icon9;
        icon9.addFile(QString::fromUtf8(":/MainWindow/Diagram.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionUpdate_axial_normale->setIcon(icon9);
        actionUse_voi = new QAction(MainWindowClass);
        actionUse_voi->setObjectName(QString::fromUtf8("actionUse_voi"));
        actionUse_voi->setCheckable(true);
        QIcon icon10;
        icon10.addFile(QString::fromUtf8(":/MainWindow/Red mark.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionUse_voi->setIcon(icon10);
        actionSave_axial_slice_to_Png = new QAction(MainWindowClass);
        actionSave_axial_slice_to_Png->setObjectName(QString::fromUtf8("actionSave_axial_slice_to_Png"));
        QIcon icon11;
        icon11.addFile(QString::fromUtf8(":/MainWindow/Downloads folder.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSave_axial_slice_to_Png->setIcon(icon11);
        actionSaveSaggitalToPng = new QAction(MainWindowClass);
        actionSaveSaggitalToPng->setObjectName(QString::fromUtf8("actionSaveSaggitalToPng"));
        actionSaveSaggitalToPng->setCheckable(true);
        actionSaveCoronalToPng = new QAction(MainWindowClass);
        actionSaveCoronalToPng->setObjectName(QString::fromUtf8("actionSaveCoronalToPng"));
        actionSaveCoronalToPng->setCheckable(true);
        actionSaveAxialToPng = new QAction(MainWindowClass);
        actionSaveAxialToPng->setObjectName(QString::fromUtf8("actionSaveAxialToPng"));
        actionSaveAxialToPng->setCheckable(true);
        actionSaveAxialToPng->setChecked(true);
        actionUpdate_volume_property_settings = new QAction(MainWindowClass);
        actionUpdate_volume_property_settings->setObjectName(QString::fromUtf8("actionUpdate_volume_property_settings"));
        actionUpdate_volume_property_settings->setCheckable(true);
        actionUpdate_volume_property_settings->setIcon(icon3);
        actionVOI_actor = new QAction(MainWindowClass);
        actionVOI_actor->setObjectName(QString::fromUtf8("actionVOI_actor"));
        actionVOI_actor->setCheckable(true);
        actionVOI_actor->setChecked(false);
        actionAxial_slice_actor = new QAction(MainWindowClass);
        actionAxial_slice_actor->setObjectName(QString::fromUtf8("actionAxial_slice_actor"));
        actionAxial_slice_actor->setCheckable(true);
        actionAxial_slice_actor->setChecked(false);
        actionSagittal_slice_actor = new QAction(MainWindowClass);
        actionSagittal_slice_actor->setObjectName(QString::fromUtf8("actionSagittal_slice_actor"));
        actionSagittal_slice_actor->setCheckable(true);
        actionSagittal_slice_actor->setChecked(false);
        actionCoronal_slice_actor = new QAction(MainWindowClass);
        actionCoronal_slice_actor->setObjectName(QString::fromUtf8("actionCoronal_slice_actor"));
        actionCoronal_slice_actor->setCheckable(true);
        actionCoronal_slice_actor->setChecked(false);
        action3D_actor = new QAction(MainWindowClass);
        action3D_actor->setObjectName(QString::fromUtf8("action3D_actor"));
        action3D_actor->setCheckable(true);
        action3D_actor->setChecked(true);
        centralWidget = new QWidget(MainWindowClass);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        centralWidget->setLayoutDirection(Qt::LeftToRight);
        verticalLayout_2 = new QVBoxLayout(centralWidget);
        verticalLayout_2->setSpacing(6);
        verticalLayout_2->setContentsMargins(11, 11, 11, 11);
        verticalLayout_2->setObjectName(QString::fromUtf8("verticalLayout_2"));
        splitter = new QSplitter(centralWidget);
        splitter->setObjectName(QString::fromUtf8("splitter"));
        splitter->setOrientation(Qt::Horizontal);
        horizontalLayoutWidget = new QWidget(splitter);
        horizontalLayoutWidget->setObjectName(QString::fromUtf8("horizontalLayoutWidget"));
        horizontalLayout = new QHBoxLayout(horizontalLayoutWidget);
        horizontalLayout->setSpacing(6);
        horizontalLayout->setContentsMargins(11, 11, 11, 11);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        horizontalLayout->setContentsMargins(0, 0, 0, 0);
        toolBox = new QToolBox(horizontalLayoutWidget);
        toolBox->setObjectName(QString::fromUtf8("toolBox"));
        toolBox->setFrameShape(QFrame::Box);
        page = new QWidget();
        page->setObjectName(QString::fromUtf8("page"));
        page->setGeometry(QRect(0, 0, 361, 364));
        verticalLayout = new QVBoxLayout(page);
        verticalLayout->setSpacing(6);
        verticalLayout->setContentsMargins(11, 11, 11, 11);
        verticalLayout->setObjectName(QString::fromUtf8("verticalLayout"));
        dicomDirView = new QTreeView(page);
        dicomDirView->setObjectName(QString::fromUtf8("dicomDirView"));

        verticalLayout->addWidget(dicomDirView);

        toolBox->addItem(page, QString::fromUtf8("Patients"));
        page_2 = new QWidget();
        page_2->setObjectName(QString::fromUtf8("page_2"));
        page_2->setGeometry(QRect(0, 0, 361, 364));
        verticalLayout_3 = new QVBoxLayout(page_2);
        verticalLayout_3->setSpacing(6);
        verticalLayout_3->setContentsMargins(11, 11, 11, 11);
        verticalLayout_3->setObjectName(QString::fromUtf8("verticalLayout_3"));
        parWindowLevelToobar = new QVBoxLayout();
        parWindowLevelToobar->setSpacing(6);
        parWindowLevelToobar->setObjectName(QString::fromUtf8("parWindowLevelToobar"));

        verticalLayout_3->addLayout(parWindowLevelToobar);

        tableWindowLevelPreset = new QTableWidget(page_2);
        if (tableWindowLevelPreset->columnCount() < 4)
            tableWindowLevelPreset->setColumnCount(4);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        tableWindowLevelPreset->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        tableWindowLevelPreset->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        tableWindowLevelPreset->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        tableWindowLevelPreset->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        if (tableWindowLevelPreset->rowCount() < 21)
            tableWindowLevelPreset->setRowCount(21);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(0, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(1, __qtablewidgetitem5);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(2, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(3, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(4, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(5, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(6, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(7, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(8, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(9, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(10, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(11, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(12, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(13, __qtablewidgetitem17);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(14, __qtablewidgetitem18);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(15, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(16, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(17, __qtablewidgetitem21);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(18, __qtablewidgetitem22);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(19, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        tableWindowLevelPreset->setVerticalHeaderItem(20, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(0, 1, __qtablewidgetitem25);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(0, 2, __qtablewidgetitem26);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(0, 3, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(1, 1, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(1, 2, __qtablewidgetitem29);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(1, 3, __qtablewidgetitem30);
        QTableWidgetItem *__qtablewidgetitem31 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(2, 1, __qtablewidgetitem31);
        QTableWidgetItem *__qtablewidgetitem32 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(2, 2, __qtablewidgetitem32);
        QTableWidgetItem *__qtablewidgetitem33 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(2, 3, __qtablewidgetitem33);
        QTableWidgetItem *__qtablewidgetitem34 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(3, 1, __qtablewidgetitem34);
        QTableWidgetItem *__qtablewidgetitem35 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(3, 2, __qtablewidgetitem35);
        QTableWidgetItem *__qtablewidgetitem36 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(3, 3, __qtablewidgetitem36);
        QTableWidgetItem *__qtablewidgetitem37 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(4, 1, __qtablewidgetitem37);
        QTableWidgetItem *__qtablewidgetitem38 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(4, 2, __qtablewidgetitem38);
        QTableWidgetItem *__qtablewidgetitem39 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(4, 3, __qtablewidgetitem39);
        QTableWidgetItem *__qtablewidgetitem40 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(5, 1, __qtablewidgetitem40);
        QTableWidgetItem *__qtablewidgetitem41 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(5, 2, __qtablewidgetitem41);
        QTableWidgetItem *__qtablewidgetitem42 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(5, 3, __qtablewidgetitem42);
        QTableWidgetItem *__qtablewidgetitem43 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(6, 1, __qtablewidgetitem43);
        QTableWidgetItem *__qtablewidgetitem44 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(6, 2, __qtablewidgetitem44);
        QTableWidgetItem *__qtablewidgetitem45 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(6, 3, __qtablewidgetitem45);
        QTableWidgetItem *__qtablewidgetitem46 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(7, 1, __qtablewidgetitem46);
        QTableWidgetItem *__qtablewidgetitem47 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(7, 2, __qtablewidgetitem47);
        QTableWidgetItem *__qtablewidgetitem48 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(7, 3, __qtablewidgetitem48);
        QTableWidgetItem *__qtablewidgetitem49 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(8, 1, __qtablewidgetitem49);
        QTableWidgetItem *__qtablewidgetitem50 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(8, 2, __qtablewidgetitem50);
        QTableWidgetItem *__qtablewidgetitem51 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(8, 3, __qtablewidgetitem51);
        QTableWidgetItem *__qtablewidgetitem52 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(9, 1, __qtablewidgetitem52);
        QTableWidgetItem *__qtablewidgetitem53 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(9, 2, __qtablewidgetitem53);
        QTableWidgetItem *__qtablewidgetitem54 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(9, 3, __qtablewidgetitem54);
        QTableWidgetItem *__qtablewidgetitem55 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(10, 1, __qtablewidgetitem55);
        QTableWidgetItem *__qtablewidgetitem56 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(10, 2, __qtablewidgetitem56);
        QTableWidgetItem *__qtablewidgetitem57 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(10, 3, __qtablewidgetitem57);
        QTableWidgetItem *__qtablewidgetitem58 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(11, 1, __qtablewidgetitem58);
        QTableWidgetItem *__qtablewidgetitem59 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(11, 2, __qtablewidgetitem59);
        QTableWidgetItem *__qtablewidgetitem60 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(11, 3, __qtablewidgetitem60);
        QTableWidgetItem *__qtablewidgetitem61 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(12, 1, __qtablewidgetitem61);
        QTableWidgetItem *__qtablewidgetitem62 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(12, 2, __qtablewidgetitem62);
        QTableWidgetItem *__qtablewidgetitem63 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(12, 3, __qtablewidgetitem63);
        QTableWidgetItem *__qtablewidgetitem64 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(13, 1, __qtablewidgetitem64);
        QTableWidgetItem *__qtablewidgetitem65 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(13, 2, __qtablewidgetitem65);
        QTableWidgetItem *__qtablewidgetitem66 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(13, 3, __qtablewidgetitem66);
        QTableWidgetItem *__qtablewidgetitem67 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(14, 1, __qtablewidgetitem67);
        QTableWidgetItem *__qtablewidgetitem68 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(14, 2, __qtablewidgetitem68);
        QTableWidgetItem *__qtablewidgetitem69 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(14, 3, __qtablewidgetitem69);
        QTableWidgetItem *__qtablewidgetitem70 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(15, 1, __qtablewidgetitem70);
        QTableWidgetItem *__qtablewidgetitem71 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(15, 2, __qtablewidgetitem71);
        QTableWidgetItem *__qtablewidgetitem72 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(15, 3, __qtablewidgetitem72);
        QTableWidgetItem *__qtablewidgetitem73 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(16, 1, __qtablewidgetitem73);
        QTableWidgetItem *__qtablewidgetitem74 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(16, 2, __qtablewidgetitem74);
        QTableWidgetItem *__qtablewidgetitem75 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(16, 3, __qtablewidgetitem75);
        QTableWidgetItem *__qtablewidgetitem76 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(17, 1, __qtablewidgetitem76);
        QTableWidgetItem *__qtablewidgetitem77 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(17, 2, __qtablewidgetitem77);
        QTableWidgetItem *__qtablewidgetitem78 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(17, 3, __qtablewidgetitem78);
        QTableWidgetItem *__qtablewidgetitem79 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(18, 1, __qtablewidgetitem79);
        QTableWidgetItem *__qtablewidgetitem80 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(18, 2, __qtablewidgetitem80);
        QTableWidgetItem *__qtablewidgetitem81 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(18, 3, __qtablewidgetitem81);
        QTableWidgetItem *__qtablewidgetitem82 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(19, 1, __qtablewidgetitem82);
        QTableWidgetItem *__qtablewidgetitem83 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(19, 2, __qtablewidgetitem83);
        QTableWidgetItem *__qtablewidgetitem84 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(19, 3, __qtablewidgetitem84);
        QTableWidgetItem *__qtablewidgetitem85 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(20, 1, __qtablewidgetitem85);
        QTableWidgetItem *__qtablewidgetitem86 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(20, 2, __qtablewidgetitem86);
        QTableWidgetItem *__qtablewidgetitem87 = new QTableWidgetItem();
        tableWindowLevelPreset->setItem(20, 3, __qtablewidgetitem87);
        tableWindowLevelPreset->setObjectName(QString::fromUtf8("tableWindowLevelPreset"));
        tableWindowLevelPreset->horizontalHeader()->setDefaultSectionSize(70);
        tableWindowLevelPreset->horizontalHeader()->setMinimumSectionSize(50);
        tableWindowLevelPreset->horizontalHeader()->setStretchLastSection(true);
        tableWindowLevelPreset->verticalHeader()->setVisible(false);

        verticalLayout_3->addWidget(tableWindowLevelPreset);

        groupBox_4 = new QGroupBox(page_2);
        groupBox_4->setObjectName(QString::fromUtf8("groupBox_4"));
        horizontalLayout_2 = new QHBoxLayout(groupBox_4);
        horizontalLayout_2->setSpacing(6);
        horizontalLayout_2->setContentsMargins(11, 11, 11, 11);
        horizontalLayout_2->setObjectName(QString::fromUtf8("horizontalLayout_2"));
        label_61 = new QLabel(groupBox_4);
        label_61->setObjectName(QString::fromUtf8("label_61"));

        horizontalLayout_2->addWidget(label_61);

        curWindow = new QLineEdit(groupBox_4);
        curWindow->setObjectName(QString::fromUtf8("curWindow"));

        horizontalLayout_2->addWidget(curWindow);

        label_62 = new QLabel(groupBox_4);
        label_62->setObjectName(QString::fromUtf8("label_62"));

        horizontalLayout_2->addWidget(label_62);

        curLevel = new QLineEdit(groupBox_4);
        curLevel->setObjectName(QString::fromUtf8("curLevel"));

        horizontalLayout_2->addWidget(curLevel);


        verticalLayout_3->addWidget(groupBox_4);

        toolBox->addItem(page_2, QString::fromUtf8("Window/Level Settings"));
        page_3 = new QWidget();
        page_3->setObjectName(QString::fromUtf8("page_3"));
        page_3->setGeometry(QRect(0, 0, 361, 364));
        verticalLayout_5 = new QVBoxLayout(page_3);
        verticalLayout_5->setSpacing(6);
        verticalLayout_5->setContentsMargins(11, 11, 11, 11);
        verticalLayout_5->setObjectName(QString::fromUtf8("verticalLayout_5"));
        parVolumePropertyToolbar = new QVBoxLayout();
        parVolumePropertyToolbar->setSpacing(6);
        parVolumePropertyToolbar->setObjectName(QString::fromUtf8("parVolumePropertyToolbar"));

        verticalLayout_5->addLayout(parVolumePropertyToolbar);

        tableVolumePropertyPreset = new QTableWidget(page_3);
        if (tableVolumePropertyPreset->columnCount() < 1)
            tableVolumePropertyPreset->setColumnCount(1);
        QTableWidgetItem *__qtablewidgetitem88 = new QTableWidgetItem();
        tableVolumePropertyPreset->setHorizontalHeaderItem(0, __qtablewidgetitem88);
        tableVolumePropertyPreset->setObjectName(QString::fromUtf8("tableVolumePropertyPreset"));
        tableVolumePropertyPreset->horizontalHeader()->setDefaultSectionSize(400);
        tableVolumePropertyPreset->verticalHeader()->setVisible(false);
        tableVolumePropertyPreset->verticalHeader()->setStretchLastSection(true);

        verticalLayout_5->addWidget(tableVolumePropertyPreset);

        toolBox->addItem(page_3, QString::fromUtf8("Volume Property Settings"));
        page_4 = new QWidget();
        page_4->setObjectName(QString::fromUtf8("page_4"));
        page_4->setGeometry(QRect(0, 0, 361, 364));
        fResliceMode = new QCheckBox(page_4);
        fResliceMode->setObjectName(QString::fromUtf8("fResliceMode"));
        fResliceMode->setGeometry(QRect(10, 10, 111, 17));
        groupBox = new QGroupBox(page_4);
        groupBox->setObjectName(QString::fromUtf8("groupBox"));
        groupBox->setGeometry(QRect(10, 40, 221, 251));
        label = new QLabel(groupBox);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(10, 40, 47, 13));
        saggital_Origin_X = new QLineEdit(groupBox);
        saggital_Origin_X->setObjectName(QString::fromUtf8("saggital_Origin_X"));
        saggital_Origin_X->setGeometry(QRect(20, 40, 51, 20));
        saggital_Origin_Y = new QLineEdit(groupBox);
        saggital_Origin_Y->setObjectName(QString::fromUtf8("saggital_Origin_Y"));
        saggital_Origin_Y->setGeometry(QRect(90, 40, 51, 20));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(80, 40, 10, 13));
        saggital_Origin_Z = new QLineEdit(groupBox);
        saggital_Origin_Z->setObjectName(QString::fromUtf8("saggital_Origin_Z"));
        saggital_Origin_Z->setGeometry(QRect(160, 40, 51, 20));
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(150, 40, 16, 16));
        saggital_UL_X = new QLineEdit(groupBox);
        saggital_UL_X->setObjectName(QString::fromUtf8("saggital_UL_X"));
        saggital_UL_X->setGeometry(QRect(20, 90, 51, 20));
        saggital_UL_Y = new QLineEdit(groupBox);
        saggital_UL_Y->setObjectName(QString::fromUtf8("saggital_UL_Y"));
        saggital_UL_Y->setGeometry(QRect(90, 90, 51, 20));
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(150, 90, 16, 16));
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(10, 90, 16, 16));
        saggital_UL_Z = new QLineEdit(groupBox);
        saggital_UL_Z->setObjectName(QString::fromUtf8("saggital_UL_Z"));
        saggital_UL_Z->setGeometry(QRect(160, 90, 51, 20));
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(80, 90, 21, 16));
        saggital_LR_Z = new QLineEdit(groupBox);
        saggital_LR_Z->setObjectName(QString::fromUtf8("saggital_LR_Z"));
        saggital_LR_Z->setGeometry(QRect(160, 140, 51, 20));
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(80, 140, 16, 16));
        saggital_LR_Y = new QLineEdit(groupBox);
        saggital_LR_Y->setObjectName(QString::fromUtf8("saggital_LR_Y"));
        saggital_LR_Y->setGeometry(QRect(90, 140, 51, 20));
        saggital_LR_X = new QLineEdit(groupBox);
        saggital_LR_X->setObjectName(QString::fromUtf8("saggital_LR_X"));
        saggital_LR_X->setGeometry(QRect(20, 140, 51, 20));
        label_8 = new QLabel(groupBox);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(10, 140, 16, 16));
        label_9 = new QLabel(groupBox);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(150, 140, 21, 16));
        label_10 = new QLabel(groupBox);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(10, 20, 47, 13));
        label_11 = new QLabel(groupBox);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(10, 70, 91, 16));
        label_12 = new QLabel(groupBox);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(10, 120, 81, 16));
        label_13 = new QLabel(groupBox);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(10, 180, 16, 16));
        saggital_N_X = new QLineEdit(groupBox);
        saggital_N_X->setObjectName(QString::fromUtf8("saggital_N_X"));
        saggital_N_X->setGeometry(QRect(20, 180, 51, 20));
        saggital_N_Y = new QLineEdit(groupBox);
        saggital_N_Y->setObjectName(QString::fromUtf8("saggital_N_Y"));
        saggital_N_Y->setGeometry(QRect(90, 180, 51, 20));
        label_14 = new QLabel(groupBox);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(10, 160, 81, 16));
        label_15 = new QLabel(groupBox);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(80, 180, 16, 16));
        saggital_N_Z = new QLineEdit(groupBox);
        saggital_N_Z->setObjectName(QString::fromUtf8("saggital_N_Z"));
        saggital_N_Z->setGeometry(QRect(160, 180, 51, 20));
        label_16 = new QLabel(groupBox);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(150, 180, 21, 16));
        label_17 = new QLabel(groupBox);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(80, 220, 16, 16));
        saggital_C_X = new QLineEdit(groupBox);
        saggital_C_X->setObjectName(QString::fromUtf8("saggital_C_X"));
        saggital_C_X->setGeometry(QRect(20, 220, 51, 20));
        label_18 = new QLabel(groupBox);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(10, 200, 81, 16));
        saggital_C_Y = new QLineEdit(groupBox);
        saggital_C_Y->setObjectName(QString::fromUtf8("saggital_C_Y"));
        saggital_C_Y->setGeometry(QRect(90, 220, 51, 20));
        label_19 = new QLabel(groupBox);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(150, 220, 21, 16));
        label_20 = new QLabel(groupBox);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(10, 220, 16, 16));
        saggital_C_Z = new QLineEdit(groupBox);
        saggital_C_Z->setObjectName(QString::fromUtf8("saggital_C_Z"));
        saggital_C_Z->setGeometry(QRect(160, 220, 51, 20));
        groupBox_2 = new QGroupBox(page_4);
        groupBox_2->setObjectName(QString::fromUtf8("groupBox_2"));
        groupBox_2->setGeometry(QRect(10, 300, 221, 251));
        label_21 = new QLabel(groupBox_2);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(10, 40, 47, 13));
        coronal_Origin_X = new QLineEdit(groupBox_2);
        coronal_Origin_X->setObjectName(QString::fromUtf8("coronal_Origin_X"));
        coronal_Origin_X->setGeometry(QRect(20, 40, 51, 20));
        coronal_Origin_Y = new QLineEdit(groupBox_2);
        coronal_Origin_Y->setObjectName(QString::fromUtf8("coronal_Origin_Y"));
        coronal_Origin_Y->setGeometry(QRect(90, 40, 51, 20));
        label_22 = new QLabel(groupBox_2);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(80, 40, 10, 13));
        coronal_Origin_Z = new QLineEdit(groupBox_2);
        coronal_Origin_Z->setObjectName(QString::fromUtf8("coronal_Origin_Z"));
        coronal_Origin_Z->setGeometry(QRect(160, 40, 51, 20));
        label_23 = new QLabel(groupBox_2);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(150, 40, 16, 16));
        coronal_UL_X = new QLineEdit(groupBox_2);
        coronal_UL_X->setObjectName(QString::fromUtf8("coronal_UL_X"));
        coronal_UL_X->setGeometry(QRect(20, 90, 51, 20));
        coronal_UL_Y = new QLineEdit(groupBox_2);
        coronal_UL_Y->setObjectName(QString::fromUtf8("coronal_UL_Y"));
        coronal_UL_Y->setGeometry(QRect(90, 90, 51, 20));
        label_24 = new QLabel(groupBox_2);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(150, 90, 16, 16));
        label_25 = new QLabel(groupBox_2);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(10, 90, 16, 16));
        coronal_UL_Z = new QLineEdit(groupBox_2);
        coronal_UL_Z->setObjectName(QString::fromUtf8("coronal_UL_Z"));
        coronal_UL_Z->setGeometry(QRect(160, 90, 51, 20));
        label_26 = new QLabel(groupBox_2);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(80, 90, 21, 16));
        coronal_LR_Z = new QLineEdit(groupBox_2);
        coronal_LR_Z->setObjectName(QString::fromUtf8("coronal_LR_Z"));
        coronal_LR_Z->setGeometry(QRect(160, 140, 51, 20));
        label_27 = new QLabel(groupBox_2);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(80, 140, 16, 16));
        coronal_LR_Y = new QLineEdit(groupBox_2);
        coronal_LR_Y->setObjectName(QString::fromUtf8("coronal_LR_Y"));
        coronal_LR_Y->setGeometry(QRect(90, 140, 51, 20));
        coronal_LR_X = new QLineEdit(groupBox_2);
        coronal_LR_X->setObjectName(QString::fromUtf8("coronal_LR_X"));
        coronal_LR_X->setGeometry(QRect(20, 140, 51, 20));
        label_28 = new QLabel(groupBox_2);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(10, 140, 16, 16));
        label_29 = new QLabel(groupBox_2);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(150, 140, 21, 16));
        label_30 = new QLabel(groupBox_2);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(10, 20, 47, 13));
        label_31 = new QLabel(groupBox_2);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(10, 70, 91, 16));
        label_32 = new QLabel(groupBox_2);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(10, 120, 81, 16));
        label_33 = new QLabel(groupBox_2);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(10, 180, 16, 16));
        coronal_N_X = new QLineEdit(groupBox_2);
        coronal_N_X->setObjectName(QString::fromUtf8("coronal_N_X"));
        coronal_N_X->setGeometry(QRect(20, 180, 51, 20));
        coronal_N_Y = new QLineEdit(groupBox_2);
        coronal_N_Y->setObjectName(QString::fromUtf8("coronal_N_Y"));
        coronal_N_Y->setGeometry(QRect(90, 180, 51, 20));
        label_34 = new QLabel(groupBox_2);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(10, 160, 81, 16));
        label_35 = new QLabel(groupBox_2);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(80, 180, 16, 16));
        coronal_N_Z = new QLineEdit(groupBox_2);
        coronal_N_Z->setObjectName(QString::fromUtf8("coronal_N_Z"));
        coronal_N_Z->setGeometry(QRect(160, 180, 51, 20));
        label_36 = new QLabel(groupBox_2);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(150, 180, 21, 16));
        label_37 = new QLabel(groupBox_2);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(80, 220, 16, 16));
        coronal_C_X = new QLineEdit(groupBox_2);
        coronal_C_X->setObjectName(QString::fromUtf8("coronal_C_X"));
        coronal_C_X->setGeometry(QRect(20, 220, 51, 20));
        label_38 = new QLabel(groupBox_2);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(10, 200, 81, 16));
        coronal_C_Y = new QLineEdit(groupBox_2);
        coronal_C_Y->setObjectName(QString::fromUtf8("coronal_C_Y"));
        coronal_C_Y->setGeometry(QRect(90, 220, 51, 20));
        label_39 = new QLabel(groupBox_2);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(150, 220, 21, 16));
        label_40 = new QLabel(groupBox_2);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(10, 220, 16, 16));
        coronal_C_Z = new QLineEdit(groupBox_2);
        coronal_C_Z->setObjectName(QString::fromUtf8("coronal_C_Z"));
        coronal_C_Z->setGeometry(QRect(160, 220, 51, 20));
        groupBox_3 = new QGroupBox(page_4);
        groupBox_3->setObjectName(QString::fromUtf8("groupBox_3"));
        groupBox_3->setGeometry(QRect(250, 40, 221, 251));
        label_41 = new QLabel(groupBox_3);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(10, 40, 47, 13));
        axial_Origin_X = new QLineEdit(groupBox_3);
        axial_Origin_X->setObjectName(QString::fromUtf8("axial_Origin_X"));
        axial_Origin_X->setGeometry(QRect(20, 40, 51, 20));
        axial_Origin_Y = new QLineEdit(groupBox_3);
        axial_Origin_Y->setObjectName(QString::fromUtf8("axial_Origin_Y"));
        axial_Origin_Y->setGeometry(QRect(90, 40, 51, 20));
        label_42 = new QLabel(groupBox_3);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(80, 40, 10, 13));
        axial_Origin_Z = new QLineEdit(groupBox_3);
        axial_Origin_Z->setObjectName(QString::fromUtf8("axial_Origin_Z"));
        axial_Origin_Z->setGeometry(QRect(160, 40, 51, 20));
        label_43 = new QLabel(groupBox_3);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(150, 40, 16, 16));
        axial_UL_X = new QLineEdit(groupBox_3);
        axial_UL_X->setObjectName(QString::fromUtf8("axial_UL_X"));
        axial_UL_X->setGeometry(QRect(20, 90, 51, 20));
        axial_UL_Y = new QLineEdit(groupBox_3);
        axial_UL_Y->setObjectName(QString::fromUtf8("axial_UL_Y"));
        axial_UL_Y->setGeometry(QRect(90, 90, 51, 20));
        label_44 = new QLabel(groupBox_3);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(150, 90, 16, 16));
        label_45 = new QLabel(groupBox_3);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(10, 90, 16, 16));
        axial_UL_Z = new QLineEdit(groupBox_3);
        axial_UL_Z->setObjectName(QString::fromUtf8("axial_UL_Z"));
        axial_UL_Z->setGeometry(QRect(160, 90, 51, 20));
        label_46 = new QLabel(groupBox_3);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(80, 90, 21, 16));
        axial_LR_Z = new QLineEdit(groupBox_3);
        axial_LR_Z->setObjectName(QString::fromUtf8("axial_LR_Z"));
        axial_LR_Z->setGeometry(QRect(160, 140, 51, 20));
        label_47 = new QLabel(groupBox_3);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(80, 140, 16, 16));
        axial_LR_Y = new QLineEdit(groupBox_3);
        axial_LR_Y->setObjectName(QString::fromUtf8("axial_LR_Y"));
        axial_LR_Y->setGeometry(QRect(90, 140, 51, 20));
        axial_LR_X = new QLineEdit(groupBox_3);
        axial_LR_X->setObjectName(QString::fromUtf8("axial_LR_X"));
        axial_LR_X->setGeometry(QRect(20, 140, 51, 20));
        label_48 = new QLabel(groupBox_3);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(10, 140, 16, 16));
        label_49 = new QLabel(groupBox_3);
        label_49->setObjectName(QString::fromUtf8("label_49"));
        label_49->setGeometry(QRect(150, 140, 21, 16));
        label_50 = new QLabel(groupBox_3);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(10, 20, 47, 13));
        label_51 = new QLabel(groupBox_3);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(10, 70, 91, 16));
        label_52 = new QLabel(groupBox_3);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(10, 120, 81, 16));
        label_53 = new QLabel(groupBox_3);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(10, 180, 16, 16));
        axial_N_X = new QLineEdit(groupBox_3);
        axial_N_X->setObjectName(QString::fromUtf8("axial_N_X"));
        axial_N_X->setGeometry(QRect(20, 180, 51, 20));
        axial_N_Y = new QLineEdit(groupBox_3);
        axial_N_Y->setObjectName(QString::fromUtf8("axial_N_Y"));
        axial_N_Y->setGeometry(QRect(90, 180, 51, 20));
        label_54 = new QLabel(groupBox_3);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(10, 160, 81, 16));
        label_55 = new QLabel(groupBox_3);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(80, 180, 16, 16));
        axial_N_Z = new QLineEdit(groupBox_3);
        axial_N_Z->setObjectName(QString::fromUtf8("axial_N_Z"));
        axial_N_Z->setGeometry(QRect(160, 180, 51, 20));
        label_56 = new QLabel(groupBox_3);
        label_56->setObjectName(QString::fromUtf8("label_56"));
        label_56->setGeometry(QRect(150, 180, 21, 16));
        label_57 = new QLabel(groupBox_3);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(80, 220, 16, 16));
        axial_C_X = new QLineEdit(groupBox_3);
        axial_C_X->setObjectName(QString::fromUtf8("axial_C_X"));
        axial_C_X->setGeometry(QRect(20, 220, 51, 20));
        label_58 = new QLabel(groupBox_3);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(10, 200, 81, 16));
        axial_C_Y = new QLineEdit(groupBox_3);
        axial_C_Y->setObjectName(QString::fromUtf8("axial_C_Y"));
        axial_C_Y->setGeometry(QRect(90, 220, 51, 20));
        label_59 = new QLabel(groupBox_3);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(150, 220, 21, 16));
        label_60 = new QLabel(groupBox_3);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(10, 220, 16, 16));
        axial_C_Z = new QLineEdit(groupBox_3);
        axial_C_Z->setObjectName(QString::fromUtf8("axial_C_Z"));
        axial_C_Z->setGeometry(QRect(160, 220, 51, 20));
        label_63 = new QLabel(page_4);
        label_63->setObjectName(QString::fromUtf8("label_63"));
        label_63->setGeometry(QRect(260, 290, 47, 13));
        slicePos = new QLineEdit(page_4);
        slicePos->setObjectName(QString::fromUtf8("slicePos"));
        slicePos->setGeometry(QRect(320, 290, 113, 20));
        label_64 = new QLabel(page_4);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(260, 320, 51, 16));
        sliceIndex = new QLineEdit(page_4);
        sliceIndex->setObjectName(QString::fromUtf8("sliceIndex"));
        sliceIndex->setGeometry(QRect(320, 320, 113, 20));
        label_67 = new QLabel(page_4);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(260, 350, 47, 13));
        yDegree = new QLineEdit(page_4);
        yDegree->setObjectName(QString::fromUtf8("yDegree"));
        yDegree->setGeometry(QRect(320, 350, 113, 20));
        planeSavePngChoice = new QToolButton(page_4);
        planeSavePngChoice->setObjectName(QString::fromUtf8("planeSavePngChoice"));
        planeSavePngChoice->setGeometry(QRect(370, 10, 16, 19));
        QIcon icon12;
        icon12.addFile(QString::fromUtf8(":/MainWindow/Load.png"), QSize(), QIcon::Normal, QIcon::Off);
        planeSavePngChoice->setIcon(icon12);
        toolBox->addItem(page_4, QString::fromUtf8("Slice Settings"));
        page_5 = new QWidget();
        page_5->setObjectName(QString::fromUtf8("page_5"));
        page_5->setGeometry(QRect(0, 0, 361, 364));
        verticalLayout_4 = new QVBoxLayout(page_5);
        verticalLayout_4->setSpacing(6);
        verticalLayout_4->setContentsMargins(11, 11, 11, 11);
        verticalLayout_4->setObjectName(QString::fromUtf8("verticalLayout_4"));
        parHounsfieldFilterToolbar = new QVBoxLayout();
        parHounsfieldFilterToolbar->setSpacing(6);
        parHounsfieldFilterToolbar->setObjectName(QString::fromUtf8("parHounsfieldFilterToolbar"));

        verticalLayout_4->addLayout(parHounsfieldFilterToolbar);

        groupBox_5 = new QGroupBox(page_5);
        groupBox_5->setObjectName(QString::fromUtf8("groupBox_5"));
        label_66 = new QLabel(groupBox_5);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(10, 60, 31, 16));
        label_65 = new QLabel(groupBox_5);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(10, 20, 16, 16));
        minHounsfieldFilter = new QDoubleSpinBox(groupBox_5);
        minHounsfieldFilter->setObjectName(QString::fromUtf8("minHounsfieldFilter"));
        minHounsfieldFilter->setGeometry(QRect(40, 20, 91, 22));
        maxHounsfieldFilter = new QDoubleSpinBox(groupBox_5);
        maxHounsfieldFilter->setObjectName(QString::fromUtf8("maxHounsfieldFilter"));
        maxHounsfieldFilter->setGeometry(QRect(40, 60, 91, 22));

        verticalLayout_4->addWidget(groupBox_5);

        toolBox->addItem(page_5, QString::fromUtf8("Hounsfield filter"));

        horizontalLayout->addWidget(toolBox);

        splitter->addWidget(horizontalLayoutWidget);
        horizontalLayoutWidget_2 = new QWidget(splitter);
        horizontalLayoutWidget_2->setObjectName(QString::fromUtf8("horizontalLayoutWidget_2"));
        horizontalLayout_3 = new QHBoxLayout(horizontalLayoutWidget_2);
        horizontalLayout_3->setSpacing(6);
        horizontalLayout_3->setContentsMargins(11, 11, 11, 11);
        horizontalLayout_3->setObjectName(QString::fromUtf8("horizontalLayout_3"));
        horizontalLayout_3->setContentsMargins(0, 0, 0, 0);
        tabWidget = new QTabWidget(horizontalLayoutWidget_2);
        tabWidget->setObjectName(QString::fromUtf8("tabWidget"));
        tab = new QWidget();
        tab->setObjectName(QString::fromUtf8("tab"));
        horizontalLayout_4 = new QHBoxLayout(tab);
        horizontalLayout_4->setSpacing(6);
        horizontalLayout_4->setContentsMargins(11, 11, 11, 11);
        horizontalLayout_4->setObjectName(QString::fromUtf8("horizontalLayout_4"));
        gridLayout = new QGridLayout();
        gridLayout->setSpacing(6);
        gridLayout->setObjectName(QString::fromUtf8("gridLayout"));
        view1 = new QVTKOpenGLWidget(tab);
        view1->setObjectName(QString::fromUtf8("view1"));

        gridLayout->addWidget(view1, 0, 0, 1, 1);

        view3 = new QVTKOpenGLWidget(tab);
        view3->setObjectName(QString::fromUtf8("view3"));

        gridLayout->addWidget(view3, 1, 1, 1, 1);

        view4 = new QVTKOpenGLWidget(tab);
        view4->setObjectName(QString::fromUtf8("view4"));

        gridLayout->addWidget(view4, 0, 1, 1, 1);

        view2 = new QVTKOpenGLWidget(tab);
        view2->setObjectName(QString::fromUtf8("view2"));

        gridLayout->addWidget(view2, 1, 0, 1, 1);


        horizontalLayout_4->addLayout(gridLayout);

        tabWidget->addTab(tab, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QString::fromUtf8("tab_2"));
        tabWidget->addTab(tab_2, QString());

        horizontalLayout_3->addWidget(tabWidget);

        horizontalLayout_3->setStretch(0, 1);
        splitter->addWidget(horizontalLayoutWidget_2);

        verticalLayout_2->addWidget(splitter);

        MainWindowClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindowClass);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 557, 21));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        menuView = new QMenu(menuBar);
        menuView->setObjectName(QString::fromUtf8("menuView"));
        menu3D_Actor_View = new QMenu(menuView);
        menu3D_Actor_View->setObjectName(QString::fromUtf8("menu3D_Actor_View"));
        MainWindowClass->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindowClass);
        mainToolBar->setObjectName(QString::fromUtf8("mainToolBar"));
        MainWindowClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindowClass);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindowClass->setStatusBar(statusBar);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuView->menuAction());
        menuFile->addAction(actionOpen_DicomDir_File);
        menuFile->addAction(actionOpen_Dicom_Folder_and_predicted_channel_file);
        menuFile->addAction(actionSave_to_Dicom);
        menuFile->addAction(actionSave_to_Stl);
        menuFile->addSeparator();
        menuFile->addAction(actionExit);
        menuView->addAction(menu3D_Actor_View->menuAction());
        menu3D_Actor_View->addAction(actionVOI_actor);
        menu3D_Actor_View->addAction(actionSagittal_slice_actor);
        menu3D_Actor_View->addAction(actionCoronal_slice_actor);
        menu3D_Actor_View->addAction(actionAxial_slice_actor);
        menu3D_Actor_View->addAction(action3D_actor);
        mainToolBar->addAction(actionOpen_DicomDir_File);
        mainToolBar->addAction(actionOpen_Dicom_Folder_and_predicted_channel_file);
        mainToolBar->addAction(actionSave_to_Dicom);
        mainToolBar->addAction(actionSave_to_Stl);
        mainToolBar->addAction(actionSave_axial_slice_to_Png);
        mainToolBar->addAction(actionUse_voi);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionAxial_move);
        mainToolBar->addAction(actionMove_to_slice);
        mainToolBar->addAction(actionUpdate_axial_normale);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionExit);

        retranslateUi(MainWindowClass);
        QObject::connect(actionExit, SIGNAL(triggered()), MainWindowClass, SLOT(close()));

        toolBox->setCurrentIndex(0);
        tabWidget->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindowClass);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindowClass)
    {
        MainWindowClass->setWindowTitle(QCoreApplication::translate("MainWindowClass", "MainWindow", nullptr));
        actionExit->setText(QCoreApplication::translate("MainWindowClass", "Exit", nullptr));
#if QT_CONFIG(tooltip)
        actionExit->setToolTip(QCoreApplication::translate("MainWindowClass", "Exit", nullptr));
#endif // QT_CONFIG(tooltip)
        actionOpen_DicomDir_File->setText(QCoreApplication::translate("MainWindowClass", "Open Dicom Folder", nullptr));
#if QT_CONFIG(tooltip)
        actionOpen_DicomDir_File->setToolTip(QCoreApplication::translate("MainWindowClass", "Open Dicom Folder", nullptr));
#endif // QT_CONFIG(tooltip)
        actionUpdate_scene->setText(QCoreApplication::translate("MainWindowClass", "Update scene", nullptr));
        actionUpdate_window_level_settings->setText(QCoreApplication::translate("MainWindowClass", "Update window/level settings", nullptr));
        actionAxial_move->setText(QCoreApplication::translate("MainWindowClass", "Axial move", nullptr));
        actionSave_to_Dicom->setText(QCoreApplication::translate("MainWindowClass", "Save to Dicom", nullptr));
        actionOpen_Dicom_Folder_and_predicted_channel_file->setText(QCoreApplication::translate("MainWindowClass", "Open Dicom Folder and predicted channel file", nullptr));
        actionSave_to_Stl->setText(QCoreApplication::translate("MainWindowClass", "Save to Stl", nullptr));
        actionApply_Hounsfield_filter->setText(QCoreApplication::translate("MainWindowClass", "Apply Hounsfield filter", nullptr));
        actionMove_to_slice->setText(QCoreApplication::translate("MainWindowClass", "Move to slice", nullptr));
        actionUpdate_axial_normale->setText(QCoreApplication::translate("MainWindowClass", "Update axial normale", nullptr));
#if QT_CONFIG(tooltip)
        actionUpdate_axial_normale->setToolTip(QCoreApplication::translate("MainWindowClass", "Update axial normale", nullptr));
#endif // QT_CONFIG(tooltip)
        actionUse_voi->setText(QCoreApplication::translate("MainWindowClass", "Use voi", nullptr));
#if QT_CONFIG(tooltip)
        actionUse_voi->setToolTip(QCoreApplication::translate("MainWindowClass", "Use voi", nullptr));
#endif // QT_CONFIG(tooltip)
        actionSave_axial_slice_to_Png->setText(QCoreApplication::translate("MainWindowClass", "Save plane to Png", nullptr));
#if QT_CONFIG(tooltip)
        actionSave_axial_slice_to_Png->setToolTip(QCoreApplication::translate("MainWindowClass", "Save plane to Png", nullptr));
#endif // QT_CONFIG(tooltip)
        actionSaveSaggitalToPng->setText(QCoreApplication::translate("MainWindowClass", "Save sagittal plane", nullptr));
#if QT_CONFIG(tooltip)
        actionSaveSaggitalToPng->setToolTip(QCoreApplication::translate("MainWindowClass", "Save sagittal plane to png file", nullptr));
#endif // QT_CONFIG(tooltip)
        actionSaveCoronalToPng->setText(QCoreApplication::translate("MainWindowClass", "Save coronal plane", nullptr));
#if QT_CONFIG(tooltip)
        actionSaveCoronalToPng->setToolTip(QCoreApplication::translate("MainWindowClass", "Save coronal plane to png file", nullptr));
#endif // QT_CONFIG(tooltip)
        actionSaveAxialToPng->setText(QCoreApplication::translate("MainWindowClass", "Save axial plane", nullptr));
#if QT_CONFIG(tooltip)
        actionSaveAxialToPng->setToolTip(QCoreApplication::translate("MainWindowClass", "Save axial plane to png file", nullptr));
#endif // QT_CONFIG(tooltip)
        actionUpdate_volume_property_settings->setText(QCoreApplication::translate("MainWindowClass", "Update volume property settings", nullptr));
#if QT_CONFIG(tooltip)
        actionUpdate_volume_property_settings->setToolTip(QCoreApplication::translate("MainWindowClass", "Update volume property settings", nullptr));
#endif // QT_CONFIG(tooltip)
        actionVOI_actor->setText(QCoreApplication::translate("MainWindowClass", "VOI actor", nullptr));
#if QT_CONFIG(tooltip)
        actionVOI_actor->setToolTip(QCoreApplication::translate("MainWindowClass", "VOI Actor view", nullptr));
#endif // QT_CONFIG(tooltip)
        actionAxial_slice_actor->setText(QCoreApplication::translate("MainWindowClass", "Axial slice actor", nullptr));
#if QT_CONFIG(tooltip)
        actionAxial_slice_actor->setToolTip(QCoreApplication::translate("MainWindowClass", "Set Axial slice actor visibility on 3D", nullptr));
#endif // QT_CONFIG(tooltip)
        actionSagittal_slice_actor->setText(QCoreApplication::translate("MainWindowClass", "Sagittal slice actor", nullptr));
#if QT_CONFIG(tooltip)
        actionSagittal_slice_actor->setToolTip(QCoreApplication::translate("MainWindowClass", "Set Sagittal slice actor visibility on 3D", nullptr));
#endif // QT_CONFIG(tooltip)
        actionCoronal_slice_actor->setText(QCoreApplication::translate("MainWindowClass", "Coronal slice actor", nullptr));
#if QT_CONFIG(tooltip)
        actionCoronal_slice_actor->setToolTip(QCoreApplication::translate("MainWindowClass", "Set Coronal slice actor visibility on 3D", nullptr));
#endif // QT_CONFIG(tooltip)
        action3D_actor->setText(QCoreApplication::translate("MainWindowClass", "3D", nullptr));
#if QT_CONFIG(tooltip)
        action3D_actor->setToolTip(QCoreApplication::translate("MainWindowClass", "Set 3D actor visibility", nullptr));
#endif // QT_CONFIG(tooltip)
        toolBox->setItemText(toolBox->indexOf(page), QCoreApplication::translate("MainWindowClass", "Patients", nullptr));
        QTableWidgetItem *___qtablewidgetitem = tableWindowLevelPreset->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QCoreApplication::translate("MainWindowClass", "Image", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = tableWindowLevelPreset->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QCoreApplication::translate("MainWindowClass", "Name", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = tableWindowLevelPreset->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QCoreApplication::translate("MainWindowClass", "Window", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = tableWindowLevelPreset->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QCoreApplication::translate("MainWindowClass", "Level", nullptr));

        const bool __sortingEnabled = tableWindowLevelPreset->isSortingEnabled();
        tableWindowLevelPreset->setSortingEnabled(false);
        QTableWidgetItem *___qtablewidgetitem4 = tableWindowLevelPreset->item(0, 1);
        ___qtablewidgetitem4->setText(QCoreApplication::translate("MainWindowClass", "Bone", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = tableWindowLevelPreset->item(0, 2);
        ___qtablewidgetitem5->setText(QCoreApplication::translate("MainWindowClass", "1500", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = tableWindowLevelPreset->item(0, 3);
        ___qtablewidgetitem6->setText(QCoreApplication::translate("MainWindowClass", "300", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = tableWindowLevelPreset->item(1, 1);
        ___qtablewidgetitem7->setText(QCoreApplication::translate("MainWindowClass", "Bone 1", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = tableWindowLevelPreset->item(1, 2);
        ___qtablewidgetitem8->setText(QCoreApplication::translate("MainWindowClass", "2000", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = tableWindowLevelPreset->item(1, 3);
        ___qtablewidgetitem9->setText(QCoreApplication::translate("MainWindowClass", "300", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = tableWindowLevelPreset->item(2, 1);
        ___qtablewidgetitem10->setText(QCoreApplication::translate("MainWindowClass", "Bone 2", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = tableWindowLevelPreset->item(2, 2);
        ___qtablewidgetitem11->setText(QCoreApplication::translate("MainWindowClass", "2000", nullptr));
        QTableWidgetItem *___qtablewidgetitem12 = tableWindowLevelPreset->item(2, 3);
        ___qtablewidgetitem12->setText(QCoreApplication::translate("MainWindowClass", "350", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = tableWindowLevelPreset->item(3, 1);
        ___qtablewidgetitem13->setText(QCoreApplication::translate("MainWindowClass", "Bone Spine", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = tableWindowLevelPreset->item(3, 2);
        ___qtablewidgetitem14->setText(QCoreApplication::translate("MainWindowClass", "1800", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = tableWindowLevelPreset->item(3, 3);
        ___qtablewidgetitem15->setText(QCoreApplication::translate("MainWindowClass", "400", nullptr));
        QTableWidgetItem *___qtablewidgetitem16 = tableWindowLevelPreset->item(4, 1);
        ___qtablewidgetitem16->setText(QCoreApplication::translate("MainWindowClass", "Liver", nullptr));
        QTableWidgetItem *___qtablewidgetitem17 = tableWindowLevelPreset->item(4, 2);
        ___qtablewidgetitem17->setText(QCoreApplication::translate("MainWindowClass", "2000", nullptr));
        QTableWidgetItem *___qtablewidgetitem18 = tableWindowLevelPreset->item(4, 3);
        ___qtablewidgetitem18->setText(QCoreApplication::translate("MainWindowClass", "-500", nullptr));
        QTableWidgetItem *___qtablewidgetitem19 = tableWindowLevelPreset->item(5, 1);
        ___qtablewidgetitem19->setText(QCoreApplication::translate("MainWindowClass", "Lung - Hard", nullptr));
        QTableWidgetItem *___qtablewidgetitem20 = tableWindowLevelPreset->item(5, 2);
        ___qtablewidgetitem20->setText(QCoreApplication::translate("MainWindowClass", "1000", nullptr));
        QTableWidgetItem *___qtablewidgetitem21 = tableWindowLevelPreset->item(5, 3);
        ___qtablewidgetitem21->setText(QCoreApplication::translate("MainWindowClass", "-600", nullptr));
        QTableWidgetItem *___qtablewidgetitem22 = tableWindowLevelPreset->item(6, 1);
        ___qtablewidgetitem22->setText(QCoreApplication::translate("MainWindowClass", "Lung - Soft", nullptr));
        QTableWidgetItem *___qtablewidgetitem23 = tableWindowLevelPreset->item(6, 2);
        ___qtablewidgetitem23->setText(QCoreApplication::translate("MainWindowClass", "1500", nullptr));
        QTableWidgetItem *___qtablewidgetitem24 = tableWindowLevelPreset->item(6, 3);
        ___qtablewidgetitem24->setText(QCoreApplication::translate("MainWindowClass", "-700", nullptr));
        QTableWidgetItem *___qtablewidgetitem25 = tableWindowLevelPreset->item(7, 1);
        ___qtablewidgetitem25->setText(QCoreApplication::translate("MainWindowClass", "Lung", nullptr));
        QTableWidgetItem *___qtablewidgetitem26 = tableWindowLevelPreset->item(7, 2);
        ___qtablewidgetitem26->setText(QCoreApplication::translate("MainWindowClass", "1500", nullptr));
        QTableWidgetItem *___qtablewidgetitem27 = tableWindowLevelPreset->item(7, 3);
        ___qtablewidgetitem27->setText(QCoreApplication::translate("MainWindowClass", "-650", nullptr));
        QTableWidgetItem *___qtablewidgetitem28 = tableWindowLevelPreset->item(8, 1);
        ___qtablewidgetitem28->setText(QCoreApplication::translate("MainWindowClass", "Soft Tissue", nullptr));
        QTableWidgetItem *___qtablewidgetitem29 = tableWindowLevelPreset->item(8, 2);
        ___qtablewidgetitem29->setText(QCoreApplication::translate("MainWindowClass", "300", nullptr));
        QTableWidgetItem *___qtablewidgetitem30 = tableWindowLevelPreset->item(8, 3);
        ___qtablewidgetitem30->setText(QCoreApplication::translate("MainWindowClass", "30", nullptr));
        QTableWidgetItem *___qtablewidgetitem31 = tableWindowLevelPreset->item(9, 1);
        ___qtablewidgetitem31->setText(QCoreApplication::translate("MainWindowClass", "Soft Tissue", nullptr));
        QTableWidgetItem *___qtablewidgetitem32 = tableWindowLevelPreset->item(9, 2);
        ___qtablewidgetitem32->setText(QCoreApplication::translate("MainWindowClass", "400", nullptr));
        QTableWidgetItem *___qtablewidgetitem33 = tableWindowLevelPreset->item(9, 3);
        ___qtablewidgetitem33->setText(QCoreApplication::translate("MainWindowClass", "40", nullptr));
        QTableWidgetItem *___qtablewidgetitem34 = tableWindowLevelPreset->item(10, 1);
        ___qtablewidgetitem34->setText(QCoreApplication::translate("MainWindowClass", "Vasculature - Hard", nullptr));
        QTableWidgetItem *___qtablewidgetitem35 = tableWindowLevelPreset->item(10, 2);
        ___qtablewidgetitem35->setText(QCoreApplication::translate("MainWindowClass", "240", nullptr));
        QTableWidgetItem *___qtablewidgetitem36 = tableWindowLevelPreset->item(10, 3);
        ___qtablewidgetitem36->setText(QCoreApplication::translate("MainWindowClass", "80", nullptr));
        QTableWidgetItem *___qtablewidgetitem37 = tableWindowLevelPreset->item(11, 1);
        ___qtablewidgetitem37->setText(QCoreApplication::translate("MainWindowClass", "Vasculature - Soft", nullptr));
        QTableWidgetItem *___qtablewidgetitem38 = tableWindowLevelPreset->item(11, 2);
        ___qtablewidgetitem38->setText(QCoreApplication::translate("MainWindowClass", "650", nullptr));
        QTableWidgetItem *___qtablewidgetitem39 = tableWindowLevelPreset->item(11, 3);
        ___qtablewidgetitem39->setText(QCoreApplication::translate("MainWindowClass", "160", nullptr));
        QTableWidgetItem *___qtablewidgetitem40 = tableWindowLevelPreset->item(12, 1);
        ___qtablewidgetitem40->setText(QCoreApplication::translate("MainWindowClass", "Mediastinum", nullptr));
        QTableWidgetItem *___qtablewidgetitem41 = tableWindowLevelPreset->item(12, 2);
        ___qtablewidgetitem41->setText(QCoreApplication::translate("MainWindowClass", "350", nullptr));
        QTableWidgetItem *___qtablewidgetitem42 = tableWindowLevelPreset->item(12, 3);
        ___qtablewidgetitem42->setText(QCoreApplication::translate("MainWindowClass", "25", nullptr));
        QTableWidgetItem *___qtablewidgetitem43 = tableWindowLevelPreset->item(13, 1);
        ___qtablewidgetitem43->setText(QCoreApplication::translate("MainWindowClass", "Ischemia", nullptr));
        QTableWidgetItem *___qtablewidgetitem44 = tableWindowLevelPreset->item(13, 2);
        ___qtablewidgetitem44->setText(QCoreApplication::translate("MainWindowClass", "15", nullptr));
        QTableWidgetItem *___qtablewidgetitem45 = tableWindowLevelPreset->item(13, 3);
        ___qtablewidgetitem45->setText(QCoreApplication::translate("MainWindowClass", "32", nullptr));
        QTableWidgetItem *___qtablewidgetitem46 = tableWindowLevelPreset->item(14, 1);
        ___qtablewidgetitem46->setText(QCoreApplication::translate("MainWindowClass", "Ischemia - Soft", nullptr));
        QTableWidgetItem *___qtablewidgetitem47 = tableWindowLevelPreset->item(14, 2);
        ___qtablewidgetitem47->setText(QCoreApplication::translate("MainWindowClass", "80", nullptr));
        QTableWidgetItem *___qtablewidgetitem48 = tableWindowLevelPreset->item(14, 3);
        ___qtablewidgetitem48->setText(QCoreApplication::translate("MainWindowClass", "20", nullptr));
        QTableWidgetItem *___qtablewidgetitem49 = tableWindowLevelPreset->item(15, 1);
        ___qtablewidgetitem49->setText(QCoreApplication::translate("MainWindowClass", "Hila, Pleura", nullptr));
        QTableWidgetItem *___qtablewidgetitem50 = tableWindowLevelPreset->item(15, 2);
        ___qtablewidgetitem50->setText(QCoreApplication::translate("MainWindowClass", "350", nullptr));
        QTableWidgetItem *___qtablewidgetitem51 = tableWindowLevelPreset->item(15, 3);
        ___qtablewidgetitem51->setText(QCoreApplication::translate("MainWindowClass", "50", nullptr));
        QTableWidgetItem *___qtablewidgetitem52 = tableWindowLevelPreset->item(16, 1);
        ___qtablewidgetitem52->setText(QCoreApplication::translate("MainWindowClass", "DICOM", nullptr));
        QTableWidgetItem *___qtablewidgetitem53 = tableWindowLevelPreset->item(16, 2);
        ___qtablewidgetitem53->setText(QCoreApplication::translate("MainWindowClass", "350", nullptr));
        QTableWidgetItem *___qtablewidgetitem54 = tableWindowLevelPreset->item(16, 3);
        ___qtablewidgetitem54->setText(QCoreApplication::translate("MainWindowClass", "0", nullptr));
        QTableWidgetItem *___qtablewidgetitem55 = tableWindowLevelPreset->item(17, 1);
        ___qtablewidgetitem55->setText(QCoreApplication::translate("MainWindowClass", "Temporal bones", nullptr));
        QTableWidgetItem *___qtablewidgetitem56 = tableWindowLevelPreset->item(17, 2);
        ___qtablewidgetitem56->setText(QCoreApplication::translate("MainWindowClass", "2800", nullptr));
        QTableWidgetItem *___qtablewidgetitem57 = tableWindowLevelPreset->item(17, 3);
        ___qtablewidgetitem57->setText(QCoreApplication::translate("MainWindowClass", "600", nullptr));
        QTableWidgetItem *___qtablewidgetitem58 = tableWindowLevelPreset->item(18, 1);
        ___qtablewidgetitem58->setText(QCoreApplication::translate("MainWindowClass", "Emphysema", nullptr));
        QTableWidgetItem *___qtablewidgetitem59 = tableWindowLevelPreset->item(18, 2);
        ___qtablewidgetitem59->setText(QCoreApplication::translate("MainWindowClass", "500", nullptr));
        QTableWidgetItem *___qtablewidgetitem60 = tableWindowLevelPreset->item(18, 3);
        ___qtablewidgetitem60->setText(QCoreApplication::translate("MainWindowClass", "-850", nullptr));
        QTableWidgetItem *___qtablewidgetitem61 = tableWindowLevelPreset->item(19, 1);
        ___qtablewidgetitem61->setText(QCoreApplication::translate("MainWindowClass", "Brain", nullptr));
        QTableWidgetItem *___qtablewidgetitem62 = tableWindowLevelPreset->item(19, 2);
        ___qtablewidgetitem62->setText(QCoreApplication::translate("MainWindowClass", "100", nullptr));
        QTableWidgetItem *___qtablewidgetitem63 = tableWindowLevelPreset->item(19, 3);
        ___qtablewidgetitem63->setText(QCoreApplication::translate("MainWindowClass", "35", nullptr));
        QTableWidgetItem *___qtablewidgetitem64 = tableWindowLevelPreset->item(20, 1);
        ___qtablewidgetitem64->setText(QCoreApplication::translate("MainWindowClass", "Predicted channel", nullptr));
        QTableWidgetItem *___qtablewidgetitem65 = tableWindowLevelPreset->item(20, 2);
        ___qtablewidgetitem65->setText(QCoreApplication::translate("MainWindowClass", "1535", nullptr));
        QTableWidgetItem *___qtablewidgetitem66 = tableWindowLevelPreset->item(20, 3);
        ___qtablewidgetitem66->setText(QCoreApplication::translate("MainWindowClass", "3071", nullptr));
        tableWindowLevelPreset->setSortingEnabled(__sortingEnabled);

        groupBox_4->setTitle(QCoreApplication::translate("MainWindowClass", "Current Settings", nullptr));
        label_61->setText(QCoreApplication::translate("MainWindowClass", "Window", nullptr));
        label_62->setText(QCoreApplication::translate("MainWindowClass", "Level", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_2), QCoreApplication::translate("MainWindowClass", "Window/Level Settings", nullptr));
        QTableWidgetItem *___qtablewidgetitem67 = tableVolumePropertyPreset->horizontalHeaderItem(0);
        ___qtablewidgetitem67->setText(QCoreApplication::translate("MainWindowClass", "Name", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_3), QCoreApplication::translate("MainWindowClass", "Volume Property Settings", nullptr));
        fResliceMode->setText(QCoreApplication::translate("MainWindowClass", "Oblique slice", nullptr));
        groupBox->setTitle(QCoreApplication::translate("MainWindowClass", "Saggital", nullptr));
        label->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        label_2->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_3->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_4->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_5->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        label_6->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_7->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_8->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        label_9->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_10->setText(QCoreApplication::translate("MainWindowClass", "Origin", nullptr));
        label_11->setText(QCoreApplication::translate("MainWindowClass", "Upper Left Point", nullptr));
        label_12->setText(QCoreApplication::translate("MainWindowClass", "Lower right Point", nullptr));
        label_13->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        label_14->setText(QCoreApplication::translate("MainWindowClass", "Normal", nullptr));
        label_15->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_16->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_17->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_18->setText(QCoreApplication::translate("MainWindowClass", "Center", nullptr));
        label_19->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_20->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        groupBox_2->setTitle(QCoreApplication::translate("MainWindowClass", "Coronal", nullptr));
        label_21->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        label_22->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_23->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_24->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_25->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        label_26->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_27->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_28->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        label_29->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_30->setText(QCoreApplication::translate("MainWindowClass", "Origin", nullptr));
        label_31->setText(QCoreApplication::translate("MainWindowClass", "Upper Left Point", nullptr));
        label_32->setText(QCoreApplication::translate("MainWindowClass", "Lower right Point", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindowClass", "Normal", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_36->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindowClass", "Center", nullptr));
        label_39->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_40->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        groupBox_3->setTitle(QCoreApplication::translate("MainWindowClass", "Axial", nullptr));
        label_41->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        label_42->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_43->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_44->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_45->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        label_46->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_47->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_48->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        label_49->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_50->setText(QCoreApplication::translate("MainWindowClass", "Origin", nullptr));
        label_51->setText(QCoreApplication::translate("MainWindowClass", "Upper Left Point", nullptr));
        label_52->setText(QCoreApplication::translate("MainWindowClass", "Lower right Point", nullptr));
        label_53->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        label_54->setText(QCoreApplication::translate("MainWindowClass", "Normal", nullptr));
        label_55->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_56->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_57->setText(QCoreApplication::translate("MainWindowClass", "Y", nullptr));
        label_58->setText(QCoreApplication::translate("MainWindowClass", "Center", nullptr));
        label_59->setText(QCoreApplication::translate("MainWindowClass", "Z", nullptr));
        label_60->setText(QCoreApplication::translate("MainWindowClass", "X", nullptr));
        label_63->setText(QCoreApplication::translate("MainWindowClass", "Slice pos", nullptr));
        label_64->setText(QCoreApplication::translate("MainWindowClass", "Slice index", nullptr));
        label_67->setText(QCoreApplication::translate("MainWindowClass", "Y Degree", nullptr));
        planeSavePngChoice->setText(QString());
        toolBox->setItemText(toolBox->indexOf(page_4), QCoreApplication::translate("MainWindowClass", "Slice Settings", nullptr));
        groupBox_5->setTitle(QCoreApplication::translate("MainWindowClass", "GroupBox", nullptr));
        label_66->setText(QCoreApplication::translate("MainWindowClass", "Max", nullptr));
        label_65->setText(QCoreApplication::translate("MainWindowClass", "Min", nullptr));
        toolBox->setItemText(toolBox->indexOf(page_5), QCoreApplication::translate("MainWindowClass", "Hounsfield filter", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QCoreApplication::translate("MainWindowClass", "Tab 1", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QCoreApplication::translate("MainWindowClass", "Tab 2", nullptr));
        menuFile->setTitle(QCoreApplication::translate("MainWindowClass", "File", nullptr));
        menuView->setTitle(QCoreApplication::translate("MainWindowClass", "View", nullptr));
        menu3D_Actor_View->setTitle(QCoreApplication::translate("MainWindowClass", "3D Actor View", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindowClass: public Ui_MainWindowClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
